//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpForSick.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonPageInfo
    {
        public int Id { get; set; }
        public string MainInfo { get; set; }
        public string Diagnosis { get; set; }
        public string MoneyInfo { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<bool> Published { get; set; }
    }
}
